# Generated by Django 6.0 on 2026-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pratos/', verbose_name='Foto do Prato'),
        ),
    ]
